In [17]:
import numpy as np

In [18]:
x=5

In [19]:
print(x)

5


In [20]:
x=np.zeros(5)
print(x)
x=np.ones(5)
print(x)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [21]:
x.shape

(5,)

In [33]:
# 1D array
x = np.array([1, 2, 3])
print(x)
print(x.shape)

[1 2 3]
(3,)


In [26]:
# write a 2D array
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [27]:
# write a 2D array with all elements 0
x=np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
x=np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
# write a 3D array
x=np.zeros((3,3,3))
print(x)
print(x.shape)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
(3, 3, 3)
